pipeline {
    agent any
    tools {
        maven "Maven"
        jdk "Java-1.8"
    }
    stages {
        stage('Initialize'){
            steps{
                echo "PATH = ${M2_HOME}/bin:${PATH}"
                echo "M2_HOME = /opt/maven"
            }
        }
        stage('Git Checkout'){
            steps {
                git url: 'https://github.com/rajuramachandra/jenkins-pipeline-example.git'
            }
        }
        stage('Build') {
            steps {
                dir("/var/lib/jenkins/workspace/pipeline/my-app/") {
                sh 'mvn clean package'
                }
            }
        }
     }
    post {
       always {
          junit(
        allowEmptyResults: true,
        testResults: '*/test-reports/.xml'
      )
      }
   } 
}
